DROP DATABASE DBMSMiniPro;

CREATE DATABASE DBMSMiniPro;

USE DBMSMiniPro;

CREATE TABLE BRANCHES(BID INT PRIMARY KEY, LOC VARCHAR(20));

CREATE TABLE COMPANY(CID INT PRIMARY KEY,CNAME VARCHAR(20));

CREATE TABLE DEPARTMENT(DID INT NOT NULL, BID INT NOT NULL, DNAME VARCHAR(20) NOT NULL, PRIMARY KEY(DID, BID), FOREIGN KEY(BID) REFERENCES BRANCHES(BID) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE PRODUCT(
  PID INT NOT NULL, 
  DID INT NOT NULL,
  CID INT NOT NULL, 
  BID INT NOT NULL, 
  PRODUCT_NAME VARCHAR(30) NOT NULL, 
  EXP_DATE DATE NOT NULL, 
  QUANTITY INT NOT NULL, 
  MIN_QTY INT NOT NULL, 
  PRICE_PER_UNIT FLOAT NOT NULL, 
  PRIMARY KEY(PID,BID,DID),
  FOREIGN KEY(CID) REFERENCES COMPANY(CID) ON UPDATE CASCADE ON DELETE CASCADE, 
  FOREIGN KEY(BID,DID) REFERENCES DEPARTMENT(BID,DID) ON UPDATE CASCADE ON DELETE CASCADE );
  
CREATE TABLE PRODUCT_SOLD(
  PID INT NOT NULL, 
  DID INT NOT NULL, 
  CID INT NOT NULL,
  BID INT NOT NULL,       
  QUANTITY INT NOT NULL,  
  TOTAL_PRICE FLOAT NOT NULL,
  QUANTITY_EXPIRED INT,
  TOTAL_PRICE_EXPIRED FLOAT, 
  PRIMARY KEY(PID,BID,DID), 
  FOREIGN KEY(CID) REFERENCES COMPANY(CID) ON UPDATE CASCADE ON DELETE CASCADE, 
FOREIGN KEY(BID,DID) REFERENCES DEPARTMENT(BID,DID) ON UPDATE CASCADE ON DELETE CASCADE );


