DROP DATABASE DBMSMiniPro;

CREATE DATABASE DBMSMiniPro;

USE DBMSMiniPro;
CREATE TABLE COMPANY(CID INT PRIMARY KEY,CNAME VARCHAR(20) NOT NULL);

CREATE TABLE BRANCHES(
  BID INT NOT NULL, 
  LOC VARCHAR(20) NOT NULL, 
  CID INT NOT NULL, 
  PRIMARY KEY(BID,CID), 
  FOREIGN KEY(CID) REFERENCES COMPANY(CID) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE DEPARTMENT( 
  DID INT NOT NULL, 
  BID INT NOT NULL, 
  CID INT NOT NULL, 
  DNAME VARCHAR(20) NOT NULL, 
  PRIMARY KEY(DID, BID, CID), 
  FOREIGN KEY(BID,CID) REFERENCES BRANCHES(BID,CID) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE PRODUCT(
  PID INT NOT NULL, 
  DID INT NOT NULL,
  CID INT NOT NULL, 
  BID INT NOT NULL, 
  PRODUCT_NAME VARCHAR(30) NOT NULL, 
  EXP_DATE DATE NOT NULL, 
  QUANTITY INT NOT NULL, 
  MIN_QTY INT NOT NULL, 
  PRICE_PER_UNIT FLOAT NOT NULL, 
  PRIMARY KEY(PID,BID,DID), 
  FOREIGN KEY(DID,BID,CID) REFERENCES DEPARTMENT (DID,BID,CID) ON UPDATE CASCADE ON DELETE CASCADE );
  
CREATE TABLE PRODUCT_SOLD(
  PID INT NOT NULL, 
  DID INT NOT NULL, 
  CID INT NOT NULL,
  BID INT NOT NULL,       
  QUANTITY INT NOT NULL,  
  TOTAL_PRICE FLOAT NOT NULL,
  QUANTITY_EXPIRED INT,
  TOTAL_PRICE_EXPIRED FLOAT, 
  PRIMARY KEY(PID,BID,DID,CID),  
  FOREIGN KEY(DID,BID,CID) REFERENCES DEPARTMENT (DID,BID,CID) ON UPDATE CASCADE ON DELETE CASCADE );
