import javax.swing.*;
import java.net.URL;
import java.awt.*;
import java.sql.*;
//import java.util.*;

class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Object[][] o;
    int cnt;
    public NewJFrame(Object[][] o1, int c) {
	o = new Object[c+10][o1[0].length];
	for(int i = 0; i<=c; i++)
	{
		for(int j = 0;j<o1[i].length;j++)
			o[i][j] = o1[i][j];
	}
	cnt = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel());
	
	jTable1.setBackground(java.awt.Color.white);
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(o,new String[]{"","","",""}));
        jTable1.setGridColor(java.awt.Color.black);
        jTable1.setOpaque(false);

	/*javax.swing.table.DefaultTableModel dtm = new javax.swing.table.DefaultTableModel(0, 0);    
        dtm.setColumnIdentifiers(new String[]{"","",""});
        jTable1.setModel(dtm);
	dtm.addRow(o);
	for(int i = 0; i<20;i++)
		dtm.addRow(new String[]{"","",""});*/

	jScrollPane1.setBackground(java.awt.Color.white);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setOpaque(false);

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}

class DBPage extends javax.swing.JFrame {

    /**
     * Creates new form DBPage
     */
	Connection con;
	int cid, bid, pid, did;
	ResultSet rs1;
    public DBPage(String logoPath, String company) {
	try{
		Class.forName("com.mysql.jdbc.Driver");
		con = DriverManager.getConnection("jdbc:mysql://localhost:3306/DBMSMiniPro", "root", "iamrahul");
		Statement stmt = con.createStatement();
		ResultSet rs = stmt.executeQuery("SELECT CID FROM COMPANY WHERE CNAME = \"" + company + "\"");
		while(rs.next())
			cid = rs.getInt(1);
		System.out.printf("\nCID: %d", cid);
		java.util.Timer timer = new java.util.Timer();
        	timer.schedule(new java.util.TimerTask() {
            		@Override
            		public void run() {
				try{
					CallableStatement stmt1 = con.prepareCall("{CALL EXPP(?)}");
					stmt1.setInt(1, cid);
				  	//rs1 = stmt.executeQuery("SELECT PRODUCT_NAME, BID, DID FROM PRODUCT WHERE EXP_DATE=CURDATE() AND CID = "+cid);
					int cnt = 0;
					rs1 = stmt1.executeQuery();
					ResultSetMetaData rsmd = rs1.getMetaData();
					//String header[] = new String[rsmd.getColumnCount()];
					rs1.last();
					int rows = rs1.getRow();
					System.out.printf("Value of Rows is : %d", rows);
					rs1.beforeFirst(); 
					Object o[][] = new Object[rows+6][rsmd.getColumnCount()];
					for(int i=1;i<=rsmd.getColumnCount();i++)
               				{
						o[cnt][i-1] = rsmd.getColumnName(i);
					}
					String value = (String)o[cnt][0];
					System.out.println("\nThe value in obeject is:" + value);
					cnt = 1;
					for(int i = 1;i<=rsmd.getColumnCount();i++)
						o[cnt][i-1] = " ";
					value = (String)o[cnt][0];
					System.out.println("\nThe value in obeject is:" + value);
                			while(rs1.next())
                			{
						cnt = cnt+1;
						System.out.printf("\n%s", rs1.getString(1));
						System.out.println("");
		    				for(int j=1; j<=rsmd.getColumnCount();j++)
		    				{
							o[cnt][j-1] = rs1.getString(j);
							value = (String)o[cnt][0];
							System.out.println("\nThe value in obeject is:" + value);
		    				}
               				 }    
					System.out.printf("\nI am Here after While!!!");
					for(int i = 0; i<=cnt;i++)
						System.out.println((String)o[i][0] +" "+ (String)o[i][1] +" "+(String)o[i][2]+" "+(String)o[i][3]);
		//for(int i = 0; i<20;i++)
			//dtm.addRow(new String[]{"",""});

               			 new NewJFrame(o, cnt).setVisible(true);
				}catch(Exception e){ System.out.println(e);e.printStackTrace();}
           		}
        	}, 0, 1000*3600);

		java.util.Timer timer1 = new java.util.Timer();
        	timer1.schedule(new java.util.TimerTask() {
            		@Override
            		public void run() {
				try{
					CallableStatement stmt1 = con.prepareCall("{CALL EXP_DECCHK(?)}");
					stmt1.setInt(1, cid);
				  	//rs1 = stmt.executeQuery("SELECT PRODUCT_NAME, BID, DID FROM PRODUCT WHERE EXP_DATE=CURDATE() AND CID = "+cid);
					int cnt = 0;
					ResultSet rs2 = stmt1.executeQuery();
					ResultSetMetaData rsmd = rs2.getMetaData();
					//String header[] = new String[rsmd.getColumnCount()];
					rs2.last();
					int rows = rs2.getRow();
					System.out.printf("Value of Rows is : %d", rows);
					rs2.beforeFirst(); 
					Object o1[][] = new Object[rows+6][rsmd.getColumnCount()];
					for(int i=1;i<=rsmd.getColumnCount();i++)
               				{
						o1[cnt][i-1] = rsmd.getColumnName(i);
					}
					String value = (String)o1[cnt][0];
					System.out.println("\nThe value in obeject is:" + value);
					cnt = 1;
					for(int i = 1;i<=rsmd.getColumnCount();i++)
						o1[cnt][i-1] = " ";
					value = (String)o1[cnt][0];
					System.out.println("\nThe value in obeject is:" + value);
                			while(rs2.next())
                			{
						cnt=cnt+1;
						System.out.printf("\n%s", rs2.getString(1));
						System.out.println("");
		    				for(int j=1; j<=rsmd.getColumnCount();j++)
		    				{
							o1[cnt][j-1] = rs2.getString(j);
							value = (String)o1[cnt][0];
							System.out.println("\nThe value in obeject is:" + value);
		    				}
               				 }    
					System.out.printf("\nI am Here after While!!!");
					for(int i = 0; i<=cnt;i++)
						System.out.println((String)o1[i][0] +" "+ (String)o1[i][1] +" "+(String)o1[i][2]+" "+(String)o1[i][3]);
			//dtm.addRow(new String[]{"",""});

               			 new NewJFrame(o1, cnt).setVisible(true);
				 stmt1 = con.prepareCall("{CALL EXP_DEC(?)}");
				 stmt1.setInt(1, cid);
				 rs2 = stmt1.executeQuery();
				}catch(Exception e){ System.out.println(e);e.printStackTrace();}
           		}
        	}, 2000, 1000*3600);	

	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);};
        initComponents(logoPath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String logoPath) {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.black);
        setBounds(new java.awt.Rectangle(0, 0, 950, 650));

        jPanel1.setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEMO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STATUS");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REPORT");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(logoPath)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(java.awt.Color.white);

        jLabel4.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        jLabel4.setText("WELCOME!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(277, 277, 277))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel4)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card2");

        jPanel4.setBackground(java.awt.Color.white);

        jLabel5.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SELECT BRANCH");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel7.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SELECT DEPARTMENT");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jComboBox3.setBackground(java.awt.Color.white);
        jComboBox3.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jComboBox3.setForeground(java.awt.Color.black);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setBackground(java.awt.Color.white);
        jComboBox4.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jComboBox4.setForeground(java.awt.Color.black);
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel19.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        jLabel19.setText("EXPIRY DEMO");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

	jTextField1.setFont(new java.awt.Font("URW Gothic L", 1, 15));
	jTextField4.setFont(new java.awt.Font("URW Gothic L", 1, 15));
	jTextField3.setFont(new java.awt.Font("URW Gothic L", 1, 15));

        jLabel21.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("PID");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel22.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("PRODUCT_NAME");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel23.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("EXPIRY DATE");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel24.setBackground(java.awt.Color.white);
        jLabel24.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("ADD PRODUCT");
        jLabel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel24MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("SELECT QUANTITY");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jComboBox5.setBackground(java.awt.Color.white);
        jComboBox5.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jComboBox5.setForeground(java.awt.Color.black);
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
	jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox5MouseEntered(evt);
            }
        });

        jLabel26.setBackground(java.awt.Color.white);
        jLabel26.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("DELETE PRODUCT");
        jLabel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel26MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel26MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField4)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(98, 98, 98))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, "card3");

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SELECT  BRANCH");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jComboBox1.setBackground(java.awt.Color.white);
        jComboBox1.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SELECT DEPARTMENT");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jComboBox2.setBackground(java.awt.Color.white);
        jComboBox2.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<NOTHING>" }));

        jLabel14.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("STATUS OF BRANCH");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.black, java.awt.Color.black));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("STATUS OF B & D");
        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.black, java.awt.Color.black));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel20MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
        });

        jScrollPane3.setBackground(java.awt.Color.white);
        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane3.setOpaque(false);

        jTable1.setBackground(java.awt.Color.white);
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel());
        jTable1.setGridColor(java.awt.Color.black);
        jTable1.setOpaque(false);
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jComboBox2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, "card4");

        jPanel6.setBackground(java.awt.Color.white);

        jPanel7.setBackground(java.awt.Color.white);

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("BEST SELLING BRANCH");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("URW Gothic L", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BEST SELLING DEPARTMENT");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("URW Gothic L", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("WORST SELLING BRANCH");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("WORST SELLING DEPT");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("MOST SOLD PRODUCT");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("LEAST SOLD PRODUCT");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("TOTAL SOLD PRODUCT");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("TOTAL LOST PRODUCT");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(java.awt.Color.white);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold> 

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TAB1:
        jLabel1.setBackground(Color.GRAY);
        jPanel2.setBackground(Color.GREEN);
        jLabel1.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TAB1:
        jLabel1.setBackground(Color.WHITE);
        jPanel2.setBackground(Color.RED);
        jLabel1.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TAB2:
        jLabel2.setBackground(Color.GRAY);
        jLabel2.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TAB2:
        jLabel2.setBackground(Color.WHITE);
        jLabel2.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TAB3:
        jLabel3.setBackground(Color.GRAY);
        jLabel3.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TAB3:
        jLabel3.setBackground(Color.WHITE);
        jLabel3.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TAB1:
        jPanel2.setBackground(Color.YELLOW);
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
	try{
		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<NOTHING>" }));
		jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<NOTHING>" }));
		Statement stmt = con.createStatement();
		ResultSet rs =  stmt.executeQuery("select count(*) from BRANCHES where CID = "+ cid);
		int len = 0;
		while(rs.next())
		{
			len = rs.getInt(1);
			System.out.printf("\nNo. of branches: %d", len);
		}
		rs = stmt.executeQuery("select LOC from BRANCHES where CID = "+ cid);
		String[] str = new String[len+1];
		str[0] = "<CHOOSE>";
		int i = 1;
		while(rs.next())
		{
			str[i++] = rs.getString(1);
			System.out.printf("\nBranch i: %s", str[i-1]);
		}
		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(str));
	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);};
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TAB2:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.add(jPanel5);
        jPanel2.repaint();
        jPanel2.revalidate();
	try{
		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<NOTHING>" }));
		jTable1.setModel(new javax.swing.table.DefaultTableModel());
		Statement stmt = con.createStatement();
		ResultSet rs =  stmt.executeQuery("select count(*) from BRANCHES where CID = "+ cid);
		int len = 0;
		while(rs.next())
		{
			len = rs.getInt(1);
			System.out.printf("\nNo. of branches: %d", len);
		}
		rs = stmt.executeQuery("select LOC from BRANCHES where CID = "+ cid);
		String[] str = new String[len+1];
		str[0] = "<CHOOSE>";
		int i = 1;
		while(rs.next())
		{
			str[i++] = rs.getString(1);
			System.out.printf("\nBranch i: %s", str[i-1]);
		}
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(str));
	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);};
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TAB3:
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.add(jPanel6);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        jLabel10.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        jLabel10.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
        jLabel12.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
        jLabel12.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        jLabel13.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
        jLabel13.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        jLabel15.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
        jLabel15.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        jLabel16.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
        jLabel16.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        // TODO add your handling code here:
        jLabel17.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        // TODO add your handling code here:
        jLabel17.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
        jLabel18.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
        jLabel18.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        //jTextArea1.setText("setText: 1");
	jTextArea1.setFont(new java.awt.Font("URW Gothic L", 0, 18));
	try{
		Statement stmt = con.createStatement();
		ResultSet rs ; 
		//stmt.executeUpdate("DROP VIEW VIEW1");
		stmt.executeUpdate("CREATE VIEW VIEW1 AS (SELECT BID, SUM(TOTAL_PRICE) AS TOTAL FROM PRODUCT_SOLD WHERE CID = "+cid+" GROUP BY BID)");
		rs = stmt.executeQuery("SELECT BID, TOTAL FROM VIEW1 WHERE TOTAL IN (SELECT MAX(TOTAL) FROM VIEW1)");
		int biD = 0;
		int total = 0;
		String loc = "";
		while(rs.next())
		{
			biD = rs.getInt(1);
			total = rs.getInt(2);
		}
		rs = stmt.executeQuery("SELECT LOC FROM BRANCHES WHERE BID = "+biD+" AND CID = "+cid);
		while(rs.next())
		{
			loc = rs.getString(1);
		}
		stmt.executeUpdate("DROP VIEW VIEW1");
		jTextArea1.setText("The Branch with ID "+biD+" and name "+loc+" is the MAXIMUM selling Branch.\n\nIt has a Total sale of "+total);
	}catch(Exception e){System.out.printf("\nSql Connection ErrorjLabel9!!!: " + e);};
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        //jTextArea1.setText("second setText: 2");
	jTextArea1.setFont(new java.awt.Font("URW Gothic L", 0, 18));
	try{
		Statement stmt = con.createStatement();
		ResultSet rs ; 
		stmt.executeUpdate("CREATE VIEW VIEW1 AS (SELECT DID, SUM(TOTAL_PRICE) AS TOTAL FROM PRODUCT_SOLD WHERE CID = "+cid+" GROUP BY DID)");
		rs = stmt.executeQuery("SELECT DID, TOTAL FROM VIEW1 WHERE TOTAL IN (SELECT MAX(TOTAL) FROM VIEW1)");
		int diD = 0;
		int total = 0;
		String dname = "";
		while(rs.next())
		{
			diD = rs.getInt(1);
			total = rs.getInt(2);
		}
		rs = stmt.executeQuery("SELECT DNAME FROM DEPARTMENT WHERE DID = "+diD+" AND CID = "+cid);
		while(rs.next())
		{
			dname = rs.getString(1);
		}
		stmt.executeUpdate("DROP VIEW VIEW1");
		jTextArea1.setText("The Department with ID "+diD+" and name "+dname+" is the MAXIMUM selling Department.\n\nIt has a Total sale of "+total);
	}catch(Exception e){System.out.printf("\nSql Connection ErrorjLabel10!!!: " + e);};
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
	jTextArea1.setFont(new java.awt.Font("URW Gothic L", 0, 18));
        try{
		Statement stmt = con.createStatement();
		ResultSet rs ; 
		stmt.executeUpdate("CREATE VIEW VIEW1 AS (SELECT BID, SUM(TOTAL_PRICE) AS TOTAL FROM PRODUCT_SOLD WHERE CID = "+cid+" GROUP BY BID)");
		rs = stmt.executeQuery("SELECT BID, TOTAL FROM VIEW1 WHERE TOTAL IN (SELECT MIN(TOTAL) FROM VIEW1)");
		int biD = 0;
		int total = 0;
		String loc = "";
		while(rs.next())
		{
			biD = rs.getInt(1);
			total = rs.getInt(2);
		}
		rs = stmt.executeQuery("SELECT LOC FROM BRANCHES WHERE BID = "+biD+" AND CID = "+cid);
		while(rs.next())
		{
			loc = rs.getString(1);
		}
		stmt.executeUpdate("DROP VIEW VIEW1");
		jTextArea1.setText("The Branch with ID "+biD+" and name "+loc+" is the MINIMUM selling Branch.\n\nIt has a Total sale of "+total);
	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);};
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:	
	jTextArea1.setFont(new java.awt.Font("URW Gothic L", 0, 18));
        try{
		Statement stmt = con.createStatement();
		ResultSet rs ; 
		stmt.executeUpdate("CREATE VIEW VIEW1 AS (SELECT DID, SUM(TOTAL_PRICE) AS TOTAL FROM PRODUCT_SOLD WHERE CID = "+cid+" GROUP BY DID)");
		rs = stmt.executeQuery("SELECT DID, TOTAL FROM VIEW1 WHERE TOTAL IN (SELECT MIN(TOTAL) FROM VIEW1)");
		int diD = 0;
		int total = 0;
		String dname = "";
		while(rs.next())
		{
			diD = rs.getInt(1);
			total = rs.getInt(2);
		}
		rs = stmt.executeQuery("SELECT DNAME FROM DEPARTMENT WHERE DID = "+diD+" AND CID = "+cid);
		while(rs.next())
		{
			dname = rs.getString(1);
		}
		stmt.executeUpdate("DROP VIEW VIEW1");
		jTextArea1.setText("The Department with ID "+diD+" and name "+dname+" is the MINIMUM selling Department.\n\nIt has a Total sale of "+total);
	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);};
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        // TODO add your handling code here:
	jTextArea1.setFont(new java.awt.Font("URW Gothic L", 0, 18));
	try{
		Statement stmt = con.createStatement();
		ResultSet rs ; 
		stmt.executeUpdate("CREATE VIEW VIEW1 AS (SELECT PID, SUM(TOTAL_PRICE) AS TOTAL FROM PRODUCT_SOLD WHERE CID = "+cid+" GROUP BY PID)");
		rs = stmt.executeQuery("SELECT PID, TOTAL FROM VIEW1 WHERE TOTAL IN (SELECT MAX(TOTAL) FROM VIEW1)");
		int piD = 0;
		int total = 0;
		String pname = "";
		while(rs.next())
		{
			piD = rs.getInt(1);
			total = rs.getInt(2);
		}
		rs = stmt.executeQuery("SELECT PRODUCT_NAME FROM PRODUCT WHERE PID = "+piD+" AND CID = "+cid);
		while(rs.next())
		{
			pname = rs.getString(1);
		}
		stmt.executeUpdate("DROP VIEW VIEW1");
		jTextArea1.setText("The Product with ID "+piD+" and name "+pname+" is the MAXIMUM selling Product.\n\nIt has a Total sale of "+total);
	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);};
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        // TODO add your handling code here:
	jTextArea1.setFont(new java.awt.Font("URW Gothic L", 0, 18));
	try{
		Statement stmt = con.createStatement();
		ResultSet rs ; 
		stmt.executeUpdate("CREATE VIEW VIEW1 AS (SELECT PID, SUM(TOTAL_PRICE) AS TOTAL FROM PRODUCT_SOLD WHERE CID = "+cid+" GROUP BY PID)");
		rs = stmt.executeQuery("SELECT PID, TOTAL FROM VIEW1 WHERE TOTAL IN (SELECT MIN(TOTAL) FROM VIEW1)");
		int piD = 0;
		int total = 0;
		String pname = "";
		while(rs.next())
		{
			piD = rs.getInt(1);
			total = rs.getInt(2);
		}
		rs = stmt.executeQuery("SELECT PRODUCT_NAME FROM PRODUCT WHERE PID = "+piD+" AND CID = "+cid);
		while(rs.next())
		{
			pname = rs.getString(1);
		}
		stmt.executeUpdate("DROP VIEW VIEW1");
		jTextArea1.setText("The Product with ID "+piD+" and name "+pname+" is the MINIMUM selling Product.\n\nIt has a Total sale of "+total);
	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);};
    }//GEN-LAST:event_jLabel16MousePressed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
        // TODO add your handling code here:
	try{
		Statement stmt = con.createStatement();
		ResultSet rs ; 
		rs = stmt.executeQuery("SELECT PS.CID, PS.PID, PS.DID, P.PRODUCT_NAME, SUM(PS.TOTAL_PRICE) FROM PRODUCT_SOLD PS, PRODUCT P WHERE P.PID = PS.PID AND PS.CID = P.CID AND P.DID = PS.DID AND PS.BID = P.BID AND PS.CID = "+cid+" AND P.CID ="+cid+" GROUP BY PS.CID, PS.PID, PS.DID, P.PRODUCT_NAME");
		int piD = 0;
		int total = 0;
		String pname = "";
		jTextArea1.setFont(new java.awt.Font("URW Gothic L", 0, 18));
		jTextArea1.setText("");
		while(rs.next())
		{
			piD = rs.getInt(2);
			pname = rs.getString(4);
			total = rs.getInt(5);
			jTextArea1.append("\nThe Product with name "+pname+" has a Total sale of "+total);
		}
	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);};
    }//GEN-LAST:event_jLabel17MousePressed

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        // TODO add your handling code here:
	try{
		Statement stmt = con.createStatement();
		ResultSet rs ; 
		rs = stmt.executeQuery("SELECT PS.CID, PS.PID, PS.DID, P.PRODUCT_NAME, SUM(PS.TOTAL_PRICE_EXPIRED) FROM PRODUCT_SOLD PS, PRODUCT P WHERE P.PID = PS.PID AND PS.CID = P.CID AND P.DID = PS.DID AND PS.BID = P.BID AND PS.CID = "+cid+" AND P.CID ="+cid+" GROUP BY PS.CID, PS.PID, PS.DID, P.PRODUCT_NAME");
		int piD = 0;
		int total = 0;
		String pname = "";
		jTextArea1.setFont(new java.awt.Font("URW Gothic L", 0, 18));
		jTextArea1.setText("");
		while(rs.next())
		{
			piD = rs.getInt(2);
			pname = rs.getString(4);
			total = rs.getInt(5);
			jTextArea1.append("\nThe Product with name "+pname+" has a Total loss of "+total);
		}
	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);};
    }//GEN-LAST:event_jLabel18MousePressed

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        jLabel14.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        jLabel14.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        // TODO add your handling code here:
        jLabel20.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        // TODO add your handling code here:
        jLabel20.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        // TODO add your handling code here:
	try{
		Statement stmt = con.createStatement();
		ResultSet rs = stmt.executeQuery("select PRODUCT_NAME, QUANTITY FROM PRODUCT WHERE BID = "+bid+" AND CID ="+ cid);
		//jTextArea2.setText("");		
		
		ResultSetMetaData rsmd = rs.getMetaData();
		javax.swing.table.DefaultTableModel dtm = new javax.swing.table.DefaultTableModel(0, 0);
		
                // add header of the table
		String header[] = new String[rsmd.getColumnCount()];
		javax.swing.table.JTableHeader jth = jTable1.getTableHeader();
		jth.setBackground(java.awt.Color.white);
		for(int i=1;i<=rsmd.getColumnCount();i++)
                {
			//String header[] = new String[] { "USN", "Name", "Marks","Fav_Sub", "Email ID"};
			header[i-1] = rsmd.getColumnName(i);
		}
                        // add header in table model     
                dtm.setColumnIdentifiers(new String[]{"",""});
                        //set model into the table object
                jTable1.setModel(dtm);
		Object obj[] = new Object[rsmd.getColumnCount()];
		obj[0] = header[0];
		obj[1] = header[1];
		//jTable1.setTableHeader(null);
		jTable1.setFont(new java.awt.Font("URW Gothic L", 0, 22));
		dtm.addRow(obj);
		dtm.addRow(new String[]{"",""});
		jTable1.setFont(new java.awt.Font("URW Gothic L", 0, 15));
                while(rs.next())
                {
		    for(int i=1; i<=rsmd.getColumnCount();i++)
		    {
			obj[i-1] = rs.getString(i);
		    }
                    dtm.addRow(obj);
                }    
		for(int i = 0; i<20;i++)
			dtm.addRow(new String[]{"",""});
		//jTable1.setTableHeader(null);
	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);e.printStackTrace();};
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MousePressed
        // TODO add your handling code here:
	try{
		Statement stmt = con.createStatement();
		ResultSet rs =  stmt.executeQuery("select DID from DEPARTMENT where DNAME = \""+ String.valueOf(jComboBox2.getSelectedItem())+"\"");
		while(rs.next())
		{
			did = rs.getInt(1);
			System.out.printf("\nDID: %d", did);
		}
		rs = stmt.executeQuery("select PRODUCT_NAME, QUANTITY FROM PRODUCT WHERE BID = "+bid+" AND CID ="+ cid+" AND DID = "+did);
		//jTextArea2.setText("");		
		
		ResultSetMetaData rsmd = rs.getMetaData();
		javax.swing.table.DefaultTableModel dtm = new javax.swing.table.DefaultTableModel(0, 0);
		
                // add header of the table
		String header[] = new String[rsmd.getColumnCount()];
		javax.swing.table.JTableHeader jth = jTable1.getTableHeader();
		jth.setBackground(java.awt.Color.white);
		for(int i=1;i<=rsmd.getColumnCount();i++)
                {
			//String header[] = new String[] { "USN", "Name", "Marks","Fav_Sub", "Email ID"};
			header[i-1] = rsmd.getColumnName(i);
		}
                        // add header in table model     
                dtm.setColumnIdentifiers(new String[]{"",""});
                        //set model into the table object
                jTable1.setModel(dtm);
		Object obj[] = new Object[rsmd.getColumnCount()];
		obj[0] = header[0];
		obj[1] = header[1];
		//jTable1.setTableHeader(null);
		jTable1.setFont(new java.awt.Font("URW Gothic L", 0, 22));
		dtm.addRow(obj);
		dtm.addRow(new String[]{"",""});
		jTable1.setFont(new java.awt.Font("URW Gothic L", 0, 15));
                while(rs.next())
                {
		    for(int i=1; i<=rsmd.getColumnCount();i++)
		    {
			obj[i-1] = rs.getString(i);
		    }
                    dtm.addRow(obj);
                }    
		for(int i = 0; i<20;i++)
			dtm.addRow(new String[]{"",""});
		//jTable1.setTableHeader(null);
	}catch(Exception e){System.out.printf("\nSql Connection Error!!!: " + e);e.printStackTrace();};
    }//GEN-LAST:event_jLabel20MousePressed
   
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
	System.out.printf("\nIN Action Performed Changed!!!");
     try{
	String selectedValue = String.valueOf(jComboBox1.getSelectedItem());
	if( !selectedValue.equals("<CHOOSE>"))
	{
		Statement stmt = con.createStatement();
		//bid = 0;
		ResultSet rs = stmt.executeQuery("SELECT BID FROM BRANCHES WHERE LOC = \"" + selectedValue + "\"");
		System.out.printf("\nSelectedValue: %s", selectedValue);
		while(rs.next())
			bid = rs.getInt(1);
		System.out.printf("\nBID: %d", bid);
		rs =  stmt.executeQuery("SELECT count(*) from DEPARTMENT where CID = "+cid+" and BID = "+ bid);

		int len = 0;
		while(rs.next())
		{
			len = rs.getInt(1);
			System.out.printf("\nNo. of Departments: %d", len);
		}
		rs = stmt.executeQuery("select DNAME from DEPARTMENT where CID = "+ cid + " AND BID = " + bid);
		String[] str = new String[len+1];
		str[0] = "<CHOOSE>";
		int i = 1;
		while(rs.next())
		{
			str[i++] = rs.getString(1);
			System.out.printf("\nDeaprtment i: %s", str[i-1]);
		}
		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(str));		
	}
       }catch(Exception e){e.printStackTrace();}
    }
    
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
	try{
	String selectedValue = String.valueOf(jComboBox3.getSelectedItem());
	if( !selectedValue.equals("<CHOOSE>"))
	{
		Statement stmt = con.createStatement();
		//bid = 0;
		ResultSet rs = stmt.executeQuery("SELECT BID FROM BRANCHES WHERE LOC = \"" + selectedValue + "\"");
		System.out.printf("\nSelectedValue: %s", selectedValue);
		while(rs.next())
			bid = rs.getInt(1);
		System.out.printf("\nBID: %d", bid);
		rs =  stmt.executeQuery("SELECT count(*) from DEPARTMENT where CID = "+cid+" and BID = "+ bid);

		int len = 0;
		while(rs.next())
		{
			len = rs.getInt(1);
			System.out.printf("\nNo. of Departments: %d", len);
		}
		rs = stmt.executeQuery("select DNAME from DEPARTMENT where CID = "+ cid + " AND BID = " + bid);
		String[] str = new String[len+1];
		str[0] = "<CHOOSE>";
		int i = 1;
		while(rs.next())
		{
			str[i++] = rs.getString(1);
			System.out.printf("\nDeaprtment i: %s", str[i-1]);
		}
		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(str));		
	}
       }catch(Exception e){e.printStackTrace();}
    }                                          

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
	jLabel24.setForeground(Color.GRAY);
    }                                     

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
	jLabel24.setForeground(Color.BLACK);
	
    }                                    

    private void jLabel24MousePressed(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:

	try{
		String ebid = String.valueOf(jComboBox3.getSelectedItem());
		String edid = String.valueOf(jComboBox4.getSelectedItem());
		String epid = jTextField1.getText();
		String epname = jTextField4.getText();
		String eexp = jTextField3.getText();
		int did=0, bid=0;
		if( epid != null)
		{
			Statement stmt = con.createStatement();
			System.out.println("\nValues of bid, cid, did, pid"+ ebid+ cid +edid+epid);
			ResultSet rs =  stmt.executeQuery("select BID from BRANCHES where LOC = \""+ ebid +"\" and CID = " + cid);
			while(rs.next())
			{
				bid = rs.getInt(1);
				System.out.printf("\nBID: %d", bid);
			}
			rs =  stmt.executeQuery("select DID from DEPARTMENT where DNAME = \""+ edid +"\" AND CID = "+cid+" AND BID = "+bid);
			while(rs.next())
			{
				did = rs.getInt(1);
				System.out.printf("\nDID: %d", did);
				System.out.printf("\nCID: %d", cid);
			}
			
			stmt.executeUpdate("INSERT INTO PRODUCT VALUES("+Integer.parseInt(epid)+", "+did+","+ bid+","+ cid+", \""+epname+"\",\'"+ eexp+"\', 50,20,200)");
			
		}
	}catch(SQLException e) {
		//if(e.getSQLState().equals(45000)){
			JOptionPane.showInputDialog(new javax.swing.JFrame(), "err");
			e.printStackTrace();

		//}
	
	}
    }                                     

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
	jLabel26.setForeground(Color.GRAY);
    }                                     

    private void jLabel26MouseExited(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
	jLabel26.setForeground(Color.BLACK);
    }                                    

    private void jLabel26MousePressed(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                            

    private void jComboBox5MouseEntered(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        try{
	String ebid = String.valueOf(jComboBox3.getSelectedItem());
	String edid = String.valueOf(jComboBox4.getSelectedItem());
	String epid = jTextField1.getText();
	int did=0, bid=0;
	if( epid != null)
	{
		Statement stmt = con.createStatement();
		System.out.println("\nValues of bid, cid, did, pid"+ ebid+ cid +edid+epid);
		ResultSet rs =  stmt.executeQuery("select BID from BRANCHES where LOC = \""+ ebid +"\" and CID = " + cid);
		while(rs.next())
		{
			bid = rs.getInt(1);
			System.out.printf("\nBID: %d", bid);
		}
		rs =  stmt.executeQuery("select DID from DEPARTMENT where DNAME = \""+ edid +"\" AND CID = "+cid+" AND BID = "+bid);
		while(rs.next())
		{
			did = rs.getInt(1);
			System.out.printf("\nDID: %d", did);
			System.out.printf("\nCID: %d", cid);
		}
		//bid = 0;
		System.out.printf("\nhere1");
		rs = stmt.executeQuery("SELECT QUANTITY FROM PRODUCT WHERE PID = "+ Integer.parseInt(epid) +" AND CID = "+cid+" AND DID = "+did+" AND BID = "+bid);
		System.out.printf("\nhere2");
		int len = 0;
		while(rs.next())
		{
			System.out.printf("\nhere3");
			len = rs.getInt(1);
			System.out.printf("\nQUANTITY IS: %d", len);
		}
		System.out.printf("\nhere4");
		String[] str = new String[len+1];
		System.out.printf("\nhere5");
		str[0] = "<CHOOSE>";
		int i = 1;
		System.out.printf("\nhere6");
		while(i<=len)
		{
			System.out.printf("\nhere7");
			str[i] = i+"";
			++i;
			System.out.printf("\nValue i: %s", str[i-1]);
		}
		System.out.printf("\nhere8");
		jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(str));	
		System.out.printf("\nhere9");	
	}
       }catch(Exception e){e.printStackTrace();}
    }    

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
class SplashDemo1 extends JFrame{
	SplashDemo1() throws Exception
	{
		JWindow window = new JWindow();
		System.out.printf("\nHere");
		window.getContentPane().add(
    		new JLabel("", new ImageIcon("/home/rahul/Downloads/Normal.GIF"), SwingConstants.CENTER));
		window.setBounds(500, 150, 300, 200);
		window.setSize(700,700);
		window.setVisible(true);
		try {
			    Thread.sleep(3000);
		} catch (InterruptedException e) {
		e.printStackTrace();
		}
		window.setVisible(false);
		
		JWindow window1 = new JWindow();
                window1.getContentPane().add(
                new JLabel("", new ImageIcon("/home/rahul/Downloads/Double_RingTest.gif"), SwingConstants.CENTER));
                window1.setBounds(0, 0, 200, 200);
                window1.setSize(200,200);
                window1.setVisible(true);
                try {
                            Thread.sleep(1000);
                } catch (InterruptedException e) {
                e.printStackTrace();
                }
                window1.setVisible(false);

		initComponents();
		window.dispose();
		window1.dispose();
	}

	private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.white);

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inventory Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon("/home/rahul/Downloads/bigbazaar-ConvertImage.jpg")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, Short.MAX_VALUE)
        );

        jPanel6.setBackground(java.awt.Color.white);
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon("/home/rahul/Downloads/SPAR-ConvertImage-ConvertImage.jpg")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(257, 257, 257))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, Short.MAX_VALUE)
        );

        jPanel7.setBackground(java.awt.Color.white);
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon("/home/rahul/Downloads/morelogo-ConvertImage.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(349, 349, 349))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {                                     
       //BY MISTAKE !!! Donot Put anythng here.
    }                                    

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {                                     
        // BIG BAZAAR
	String logoPath = "/home/rahul/Downloads/bigbazaar-ConvertImage-ConvertImage.jpg";
	new DBPage(logoPath, "BigBazar").setVisible(true);
    }                                    

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {                                     
        // SPAR
	String logoPath= "/home/rahul/Downloads/SPAR-ConvertImage-ConvertImage-ConvertImage.jpg";
	new DBPage(logoPath, "Spar").setVisible(true);
    }                                    

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {                                     
        // MORE STORE
	String logoPath= "/home/rahul/Downloads/morelogo-ConvertImage-ConvertImage.png";
	new DBPage(logoPath, "More").setVisible(true);
    }                                    

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {                                     
        // BigBazaar Panel
        jPanel3.setBackground(Color.GRAY);
    }                                    

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {                                     
        // Spar Panel
        jPanel6.setBackground(Color.GRAY);
    }                                    

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {                                     
        // More Panel
        jPanel7.setBackground(Color.GRAY);
    }                                    

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {                                    
        // Big Bazaar Panel
        jPanel3.setBackground(Color.WHITE);
    }                                   

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {                                    
        // Spar Panel
        jPanel6.setBackground(Color.WHITE);
    }                                   

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {                                    
        // MORE Panel
        jPanel7.setBackground(Color.WHITE);
    }                                   

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {                                     
        jPanel3.setBackground(Color.GRAY);
    }                                    

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {                                    
        jPanel3.setBackground(Color.WHITE);
    }                                   

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        jPanel6.setBackground(Color.GRAY);
    }                                    

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        jPanel6.setBackground(Color.WHITE);
    }                                   

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        jPanel7.setBackground(Color.GRAY);
    }                                    

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        jPanel7.setBackground(Color.WHITE);
    }                          
	
	public static void main(String[] args) throws Exception
	{
		 try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //java.util.logging.Logger.getLogger(DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //java.util.logging.Logger.getLogger(DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(DGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
		new SplashDemo1().setVisible(true);	
	}

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
}
